### ISSUE TITLE
pychopmarg packages in src directory

### ISSUE THREAD

**Issue by Mvitali23** [capn-freako/PyChOpMarg#14]
Hi,
the imports in PyChOpMarg_8023dj.ipynb assume the installation of PyChOpMarg package in the environment. However, it is interesting to import directly the files in src directory for quick tests. This could be done by adding "src." before the import statements

e.g.

from src.pychopmarg.com         import COM, OptMode

instead of
from pychopmarg.com         import COM, OptMode

It could be a nice extension to add a flag to select which package to import.
Anyway thank you for this great job! 

Best regards,
Marco

**Comment by capn-freako** [comment]
Hi @Mvitali23 ,

Thanks for your interest in _PyChOpMarg_!

The more Pythonic way of doing what you're proposing is to install the package in "editable" mode:

`PyChOpMarg/ > pip install -e .`

That will allow you to run the notebook without modification, but still see the effect of any changes you make to the source code in "real time".
It is how I do development, actually.

Best regards,
-db

**Comment by Mvitali23** [comment]
Good suggestion, thank you.

Marco
